name: Test Reports Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:    
  tests:
    runs-on: ubuntu-latest
    
    steps:
      - name: Build
        run: mvn clean package

      - name: Build Success  
        run: echo "BUILD SUCCESS"

      - name: Test
        run: mvn test
      
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            test-results/**/*.xml
            test-results/**/*.trx
            test-results/**/*.json  